import os
import base64
from pathlib import Path
from github import Github, GithubException, InputGitTreeElement, Auth
from tools.file_writer import get_output_path, iter_project_files


# File extensions treated as text; everything else is uploaded as base64 blobs.
_TEXT_EXTS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".html", ".css", ".json", ".md",
    ".txt", ".yml", ".yaml", ".toml", ".cfg", ".ini", ".env", ".sh", ".gitignore",
}


def _read_file(path: Path) -> tuple[str, str]:
    """Return (content, encoding) where encoding is 'utf-8' or 'base64'."""
    if path.suffix.lower() in _TEXT_EXTS or path.suffix == "":
        try:
            return path.read_text(encoding="utf-8"), "utf-8"
        except (UnicodeDecodeError, OSError):
            pass
    return base64.b64encode(path.read_bytes()).decode("ascii"), "base64"


def push_to_github(project_title: str, repo_name: str = None, private: bool = True) -> dict:
    """Create a GitHub repo and upload all generated files for a project.

    Returns {"ok": bool, "repo_url": str, "files_pushed": int, "error": str | None}.
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        return {"ok": False, "error": "GITHUB_TOKEN not set in .env", "repo_url": "", "files_pushed": 0}

    base = get_output_path(project_title)
    if not base.exists():
        return {"ok": False, "error": "No generated files found for this project.", "repo_url": "", "files_pushed": 0}

    files = iter_project_files(base)  # excludes __pycache__, .pytest_cache, etc.
    if not files:
        return {"ok": False, "error": "Output directory is empty.", "repo_url": "", "files_pushed": 0}

    g = Github(auth=Auth.Token(token))
    try:
        user = g.get_user()
        name = repo_name or base.name

        # Reuse the repo if it already exists, otherwise create it.
        try:
            repo = user.get_repo(name)
        except GithubException:
            repo = user.create_repo(
                name,
                private=private,
                description=f"Hackathon project '{project_title}' generated by HackathonBot",
                auto_init=True,
            )

        # Build a single commit via the Git Data API (one tree, one commit).
        elements = []
        for f in files:
            rel = f.relative_to(base).as_posix()
            content, encoding = _read_file(f)
            if encoding == "utf-8":
                blob = repo.create_git_blob(content, "utf-8")
            else:
                blob = repo.create_git_blob(content, "base64")
            elements.append(InputGitTreeElement(path=rel, mode="100644", type="blob", sha=blob.sha))

        ref = repo.get_git_ref("heads/" + repo.default_branch)
        base_commit = repo.get_git_commit(ref.object.sha)
        new_tree = repo.create_git_tree(elements, base_commit.tree)
        new_commit = repo.create_git_commit(
            f"Add HackathonBot-generated project: {project_title}",
            new_tree,
            [base_commit],
        )
        ref.edit(new_commit.sha)

        return {"ok": True, "repo_url": repo.html_url, "files_pushed": len(elements), "error": None}

    except GithubException as e:
        msg = e.data.get("message", str(e)) if isinstance(e.data, dict) else str(e)
        return {"ok": False, "error": f"GitHub API error: {msg}", "repo_url": "", "files_pushed": 0}
    except Exception as e:
        return {"ok": False, "error": str(e), "repo_url": "", "files_pushed": 0}
